package metpv11_parser

case class Data(
  month: Int,
  day: Int,
  // 00001
  globalSolarRadiations: List[Int],
  maxGlobalSolarRadiation: Int,
  accumGlobalSolarRadiation: Int,
  // 00002
  directSolarRadiations: List[Int],
  maxDirectSolarRadiation: Int,
  accumDirectSolarRadiation: Int,
  // 00003
  diffuseSolarIrradiances: List[Int],
  maxDiffuseSolarIrradiance: Int,
  accumDiffuseSolarIrradiances: Int,
  // 00004
  daylightHours: List[Int],
  maxDaylightHour: Int,
  accumDaylightHour: Int,
  // 00005
  temperatures: List[Int],
  maxTemperature: Int,
  minTemperature: Int,
  averageTemperature: Int,
  // 00006
  windDirections: List[Int],
  maxWindDirection: Int,
  // 00007
  windSpeeds: List[Int],
  maxWindSpeed: Int,
  averageWindSpeed: Int,
  // 00008
  precipitations: List[Int],
  maxPrecipitation: Int,
  accumPrecipitation: Int,
  // 00009
  snowDepths: List[Int],
  maxSnowDepth: Int,
  dayNumber: Int)
